version: "2.4"
services:
  clair-db:
    image: arminc/clair-db:latest
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      clair:
        aliases:
          - postgres
  clair:
    image: arminc/clair-local-scan:latest
    ports:
    - "6060-6061:6060-6061"
    depends_on:
      clair-db:
        condition: service_healthy
    networks:
      - clair

networks:
  clair:
